### ISSUE TITLE
How to cite aminode in my manuscript?

### ISSUE THREAD

**Issue by Shicheng-Guo** [aminodektc/Downloads#1]
How to cite aminode in my manuscript?

**Comment by aminodektc** [comment]
Hello, thanks for your interest in Aminode! Here's some links that you might find helpful:

Aminode "Cite Us" Page:
http://www.aminode.org/cite

Web version of the paper:
https://www.nature.com/articles/s41598-018-19744-w

Aminode .ris file:
https://www.nature.com/articles/s41598-018-19744-w.ris

Sincerely,
Kevin
